version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro #Timezone Config / Do Not Change
      - /etc/motioneye:/etc/motioneye #Config Storage
      - /var/lib/motioneye:/var/lib/motioneye  #File Storage
    ports:
      - 8065:8765
    restart: unless-stopped
